# Generated by Django 5.1.7 on 2025-03-14 09:08

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDepartament', '0002_alter_department_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='EmployeeDepartament.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='EmployeeDepartament.department'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'parent')},
        ),
    ]
